/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */
module Hz2(input CLK, input nRST, output Hz2);

reg [23:0] divCounter;

always @(posedge CLK or negedge nRST) begin
    if (!nRST) begin
        divCounter <= 24'd0;
    end
    else if(divCounter==24'd13499999) begin
        divCounter <= 0;
    end
    else
        divCounter <= divCounter+1;
end

assign Hz2 = (divCounter==24'd13499999);

endmodule
module DIG_D_FF_1bit
#(
    parameter Default = 0
)
(
   input D,
   input C,
   output Q,
   output \~Q
);
    reg state;

    assign Q = state;
    assign \~Q = ~state;

    always @ (posedge C) begin
        state <= D;
    end

    initial begin
        state = Default;
    end
endmodule


module Mux_2x1
(
    input [0:0] sel,
    input in_0,
    input in_1,
    output reg out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule


module mydesign (
  input CLK,
  input [3:0] SW,
  input [3:0] BT,
  input nRST,
  output [3:0] DISP3,
  output [3:0] DISP2,
  output [3:0] DISP1,
  output [3:0] DISP0,
  output [7:0] LED,
  output [5:0] BOARD_LED
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  assign DISP3 = 4'b0;
  assign DISP2 = 4'b0;
  assign DISP1 = 4'b0;
  assign BOARD_LED = 6'b0;
  // Hz2
  Hz2 Hz2_i0 (
    .CLK( CLK ),
    .nRST( nRST ),
    .Hz2( s0 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i1 (
    .D( s2 ),
    .C( CLK ),
    .Q( s1 ),
    .\~Q ( s3 )
  );
  Mux_2x1 Mux_2x1_i2 (
    .sel( s0 ),
    .in_0( s1 ),
    .in_1( s3 ),
    .out( s2 )
  );
  //assign LED[0] = s1;
  //assign LED[7:1] = 7'b0;
endmodule
